### ISSUE TITLE
Rule EC7 detects object (__init__) with one argument as a setter 

### ISSUE THREAD

**Issue by AghilesAzzoug** [green-code-initiative/ecoCode-python#17]
Rule EC7 (AvoidGettersAndSetters) detects `__init__` methods with one argument and assignment as a setter.

**To Reproduce**
Code that can reproduce the error:

```python
class Something:
    def __init__(self, value):
        self.value = value
...
```

**Expected behavior**
It shouldn't be detected as a code smell since `init` method is used to assign values to object properties.

**Software Versions**
- SonarQube Version: 9.9
- Plugin Version: 1.4.0

**Comment by dedece35** [comment]
Hi @AghilesAzzoug ,

thank you for your issue. you agree it's a bug.
the correction is done in related PR.
I'm waiting for core team reviewer.
