### ISSUE TITLE
Sonarqube compatibility 10.5.x NOT OK + upgrade to 10.6

### ISSUE THREAD

**Issue by dedece35** [green-code-initiative/ecoCode-python#24]
Compatibility with Sonarqube 10.4.1 OK => test-project raises ecocode issues on local dockerized Sonarqube

Compatibility with SonarQube 10.5.0 and 10.5.1 NOT OK : 
- installation of plugin OK
- Sonarqube started OK
- installation of Python profile OK
- scan test-project and send metrics to local dockerized Sonarqube NOT OK : no ecocode issue raised, only native Sonar issues raised

ideas : 
- version of python plugin on server ?
- version of maven scanner on test-project ?

Add 10.6 SonarQube compatibility

**Comment by rrousset-michelin** [comment]
Hello,
I found what was the problem with this issue but i can't create a branch on the project.
Can you allow me to do it please.
Best regards

**Comment by rrousset-michelin** [comment]
I created the following PR: https://github.com/green-code-initiative/ecoCode-python/pull/32

**Comment by dedece35** [comment]
correction ok with linked PR

**Comment by dedece35** [comment]
Hi @rrousset-michelin,
new python plugin has just been released now with 1.5.0 version.
a new PR to SonarQube official repository has been done for offical marketplace : https://github.com/SonarSource/sonar-update-center-properties/pull/600 
Waiting for review from SonarQube team.
