### ISSUE TITLE
[EC89] Avoid using function cache without limit

### ISSUE THREAD

**Issue by Flow35650** [green-code-initiative/ecoCode-python#26]
Description:
If a function has decorators without max size cache, the program will store unlimited datas 

Solution:
To warn the developer about this cache bad habit, we have to add a new rule on the following decorators:
- @cache
- @lru_cache(maxsize=None)

Additional context:
Problem discussed with @dedece35 during ecoCode Challenge 24. Initially based on the issue CRPYT204 in kanban board

**Comment by dedece35** [comment]
Hi @B3ND3L,

please see my review feedback in PR https://github.com/green-code-initiative/ecoCode/pull/327
